import { Hotel, Kiosk, DashboardMetrics } from '@/types/schema';

export const MOCK_METRICS: DashboardMetrics = {
    totalHotels: 12,
    activeKiosks: 18,
    totalRevenue: 1250000,
    criticalAlerts: 3,
};

export const MOCK_HOTELS: Hotel[] = [
    {
        id: 'h-001',
        name: 'Royal Orchid Bangalore',
        location: 'Bangalore, KA',
        status: 'active',
        plan: 'advanced',
        kioskCount: 4,
        mrr: 50000,
        contractRenewalDate: '2025-12-01',
        contactEmail: 'ops@royalorchid.com',
    },
    {
        id: 'h-002',
        name: 'Lemon Tree Premier',
        location: 'Mumbai, MH',
        status: 'suspended',
        plan: 'standard',
        kioskCount: 2,
        mrr: 25000,
        contractRenewalDate: '2024-03-01',
        contactEmail: 'manager@lemontree.com',
    },
    {
        id: 'h-003',
        name: 'Ginger Hotel, Panjim',
        location: 'Goa',
        status: 'active',
        plan: 'standard',
        kioskCount: 1,
        mrr: 15000,
        contractRenewalDate: '2026-02-15',
        contactEmail: 'gm-goa@ginger.com',
    },
    {
        id: 'h-004',
        name: 'Sayaji Hotel',
        location: 'Indore, MP',
        status: 'onboarding',
        plan: 'advanced',
        kioskCount: 0,
        mrr: 0,
        contractRenewalDate: '2026-06-01',
        contactEmail: 'projects@sayaji.com',
    },
    {
        id: 'h-005',
        name: 'Taj Palace',
        location: 'New Delhi',
        status: 'active',
        plan: 'advanced',
        kioskCount: 3,
        mrr: 75000,
        contractRenewalDate: '2026-03-15',
        contactEmail: 'ops@tajpalace.com',
    },
    {
        id: 'h-006',
        name: 'ITC Maratha',
        location: 'Mumbai, MH',
        status: 'active',
        plan: 'advanced',
        kioskCount: 2,
        mrr: 50000,
        contractRenewalDate: '2026-04-01',
        contactEmail: 'manager@itcmaratha.com',
    },
    {
        id: 'h-007',
        name: 'Radisson Blu',
        location: 'Chennai, TN',
        status: 'active',
        plan: 'standard',
        kioskCount: 2,
        mrr: 30000,
        contractRenewalDate: '2026-05-20',
        contactEmail: 'ops@radissonchennai.com',
    },
    {
        id: 'h-008',
        name: 'Marriott Suites',
        location: 'Hyderabad, TS',
        status: 'active',
        plan: 'advanced',
        kioskCount: 3,
        mrr: 60000,
        contractRenewalDate: '2026-07-10',
        contactEmail: 'gm@marriotthyd.com',
    },
    {
        id: 'h-009',
        name: 'Holiday Inn',
        location: 'Pune, MH',
        status: 'active',
        plan: 'standard',
        kioskCount: 1,
        mrr: 15000,
        contractRenewalDate: '2026-08-01',
        contactEmail: 'ops@holidayinnpune.com',
    },
    {
        id: 'h-010',
        name: 'The Leela Palace',
        location: 'Udaipur, RJ',
        status: 'active',
        plan: 'advanced',
        kioskCount: 2,
        mrr: 80000,
        contractRenewalDate: '2026-09-15',
        contactEmail: 'gm@leelapalace.com',
    },
    {
        id: 'h-011',
        name: 'Oberoi Grand',
        location: 'Kolkata, WB',
        status: 'pending',
        plan: 'advanced',
        kioskCount: 0,
        mrr: 0,
        contractRenewalDate: '2026-10-01',
        contactEmail: 'projects@oberoi.com',
    },
    {
        id: 'h-012',
        name: 'Trident Nariman',
        location: 'Mumbai, MH',
        status: 'active',
        plan: 'standard',
        kioskCount: 1,
        mrr: 20000,
        contractRenewalDate: '2026-11-20',
        contactEmail: 'ops@trident.com',
    },
];

export const MOCK_KIOSKS: Kiosk[] = [
    {
        id: 'k-101',
        serialNumber: 'ATC-SN-9988',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: 'h-001',
        assignedHotelName: 'Royal Orchid Bangalore',
        firmwareVersion: '2.4.1',
        status: 'online',
        lastHeartbeat: '5 mins ago',
    },
    {
        id: 'k-102',
        serialNumber: 'ATC-SN-7766',
        model: 'Kiosk-V1',
        assignedHotelId: 'h-002',
        assignedHotelName: 'Lemon Tree Premier',
        firmwareVersion: '1.0.0',
        status: 'offline',
        lastHeartbeat: '24 hours ago',
    },
    {
        id: 'k-103',
        serialNumber: 'ATC-SN-5544',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: null,
        assignedHotelName: 'Inventory',
        firmwareVersion: '2.5.0',
        status: 'online',
        lastHeartbeat: '2 mins ago',
    },
    {
        id: 'k-104',
        serialNumber: 'ATC-SN-3322',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: 'h-001',
        assignedHotelName: 'Royal Orchid Bangalore',
        firmwareVersion: '2.4.1',
        status: 'online',
        lastHeartbeat: '1 min ago',
    },
    {
        id: 'k-105',
        serialNumber: 'ATC-SN-1100',
        model: 'Kiosk-V1',
        assignedHotelId: 'h-003',
        assignedHotelName: 'Ginger Hotel, Panjim',
        firmwareVersion: '1.2.0',
        status: 'warning',
        lastHeartbeat: '45 mins ago',
    },
    {
        id: 'k-106',
        serialNumber: 'ATC-SN-8877',
        model: 'Kiosk-V3-Pro',
        assignedHotelId: 'h-005',
        assignedHotelName: 'Taj Palace',
        firmwareVersion: '3.0.1',
        status: 'online',
        lastHeartbeat: '3 mins ago',
    },
    {
        id: 'k-107',
        serialNumber: 'ATC-SN-6655',
        model: 'Kiosk-V3-Pro',
        assignedHotelId: 'h-005',
        assignedHotelName: 'Taj Palace',
        firmwareVersion: '3.0.1',
        status: 'online',
        lastHeartbeat: '8 mins ago',
    },
    {
        id: 'k-108',
        serialNumber: 'ATC-SN-4433',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: 'h-006',
        assignedHotelName: 'ITC Maratha',
        firmwareVersion: '2.5.0',
        status: 'online',
        lastHeartbeat: '12 mins ago',
    },
    {
        id: 'k-109',
        serialNumber: 'ATC-SN-2211',
        model: 'Kiosk-V1',
        assignedHotelId: 'h-007',
        assignedHotelName: 'Radisson Blu',
        firmwareVersion: '1.3.0',
        status: 'offline',
        lastHeartbeat: '3 days ago',
    },
    {
        id: 'k-110',
        serialNumber: 'ATC-SN-9900',
        model: 'Kiosk-V3-Pro',
        assignedHotelId: 'h-008',
        assignedHotelName: 'Marriott Suites',
        firmwareVersion: '3.1.0',
        status: 'online',
        lastHeartbeat: '1 min ago',
    },
    {
        id: 'k-111',
        serialNumber: 'ATC-SN-7788',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: 'h-008',
        assignedHotelName: 'Marriott Suites',
        firmwareVersion: '2.5.0',
        status: 'warning',
        lastHeartbeat: '1 hour ago',
    },
    {
        id: 'k-112',
        serialNumber: 'ATC-SN-5566',
        model: 'Kiosk-V1',
        assignedHotelId: 'h-009',
        assignedHotelName: 'Holiday Inn',
        firmwareVersion: '1.2.0',
        status: 'online',
        lastHeartbeat: '15 mins ago',
    },
    {
        id: 'k-113',
        serialNumber: 'ATC-SN-3344',
        model: 'Kiosk-V3-Pro',
        assignedHotelId: 'h-010',
        assignedHotelName: 'The Leela Palace',
        firmwareVersion: '3.1.0',
        status: 'online',
        lastHeartbeat: '4 mins ago',
    },
    {
        id: 'k-114',
        serialNumber: 'ATC-SN-1122',
        model: 'Kiosk-V3-Pro',
        assignedHotelId: 'h-010',
        assignedHotelName: 'The Leela Palace',
        firmwareVersion: '3.1.0',
        status: 'online',
        lastHeartbeat: '6 mins ago',
    },
    {
        id: 'k-115',
        serialNumber: 'ATC-SN-0099',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: 'h-012',
        assignedHotelName: 'Trident Nariman',
        firmwareVersion: '2.4.1',
        status: 'online',
        lastHeartbeat: '20 mins ago',
    },
    {
        id: 'k-116',
        serialNumber: 'ATC-SN-8866',
        model: 'Kiosk-V1',
        assignedHotelId: null,
        assignedHotelName: 'Inventory',
        firmwareVersion: '1.3.0',
        status: 'online',
        lastHeartbeat: '2 mins ago',
    },
    {
        id: 'k-117',
        serialNumber: 'ATC-SN-6644',
        model: 'Kiosk-V2-Voice',
        assignedHotelId: 'h-001',
        assignedHotelName: 'Royal Orchid Bangalore',
        firmwareVersion: '2.5.0',
        status: 'online',
        lastHeartbeat: '7 mins ago',
    },
    {
        id: 'k-118',
        serialNumber: 'ATC-SN-4422',
        model: 'Kiosk-V3-Pro',
        assignedHotelId: 'h-005',
        assignedHotelName: 'Taj Palace',
        firmwareVersion: '3.0.1',
        status: 'warning',
        lastHeartbeat: '2 hours ago',
    },
];